### ISSUE TITLE
Visualize the apps

### ISSUE THREAD

**Issue by MarcSkovMadsen** [jvkloc/holoviz_panel_demonstrations#1]
Hi @jvkloc 

Thanks for sharing this repository.

To take it to the next level it would be nice with a video showing what this was or the applications deployed.

An easy way to deploy them is to use `panel convert *.py --to pyodide-worker --out apps` and then configure your repository to share the folder `apps` as the content of github pages for your repository.

Reference: https://panel.holoviz.org/how_to/wasm/convert.html

**Comment by jvkloc** [comment]
I added a repository containing the app during the development of which I saved the snippets in this repository. See https://github.com/jvkloc/data_assimilation_and_query_tool I'll refactor it a bit more but it is already a usable program as it is now if the conection parameters are supplied by whoever wants to use it. 

Real use is of course impossible unless the user has access to a specific program producing Excel files from which the data-assimilation is executed. But the program can be launched to see the Panel GUI.
